### ISSUE TITLE
pak tafel crash

### ISSUE THREAD

**Issue by DiederickKaaij** [otech-nl/adventure#1]
Als ik in de keuken de tafel probeer op te pakken crasht de game met de volgende error:
Traceback (most recent call last):
  File "shell.py", line 51, in <module>
    shell.run()
  File "shell.py", line 41, in run
    self.parse(cmd)
  File "shell.py", line 24, in parse
    self.game.get(cmd[1])
  File "C:\Users\SEY\Desktop\Python code\rene\adventure\game.py", line 49, in get
    self.items.append(self.location.items[item])
AttributeError: 'dict' object has no attribute 'append'

Stappen: 
(-start virtualenv met pipenv shell)
-run game volgens instructies (python shell.py data/test_game.json
-typ pak tafel

**Comment by otech-nl** [comment]
Duplicaat van #2
